### ISSUE TITLE
Integrate cli package into demo

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci-rpgf#12]
### Description

As a user I'd like to use `maci-cli` package for my frontend app.

### Acceptance criteria

- [ ] Support user signups (`signup` w/ MACI contract)
- [ ] Support user votes (`publishMessage` w/ Poll contract)
- [ ] Support displaying all the information related to poll (ethers)

**Comment by samajammin** [comment]
This issue seems redundant with others...

> ### Description
> As a user I'd like to use `maci-cli` package for my frontend app.
> 
> ### Acceptance criteria
> * [ ]  Support user signups (`signup` w/ MACI contract)
> * [ ]  Support user votes (`publishMessage` w/ Poll contract)
> * [ ]  Support displaying all the information related to poll (ethers)

@0xmad @kittybest @ctrlc03 LMK if I'm missing something but seems this is covered in:
- https://github.com/privacy-scaling-explorations/maci-rpgf/issues/4
- https://github.com/privacy-scaling-explorations/maci-rpgf/issues/7
- https://github.com/privacy-scaling-explorations/maci-rpgf/issues/11

Closing this out but feel free to re-open & explain what's different here.
