### ISSUE TITLE
Not getting correct poll information if not connected

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#154]
**Description**
Not sure if this happened often, but sometimes if I didn't connect my wallet and sign up, it would always be "voting is ended".

**Comment by ctrlc03** [comment]
> **Description** Not sure if this happened often, but sometimes if I didn't connect my wallet and sign up, it would always be "voting is ended".

so if you connect your wallet you will see this info (I can) no need to signup. this is because it interacts with the chain here: https://github.com/privacy-scaling-explorations/maci-rpgf/blob/main/src/contexts/Maci.tsx#L280
eventually we can start using a subgraph for this so no need to be connected
