### ISSUE TITLE
Voting flow

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#7]
As a user/badgeholder, I want to submit my ballot to vote on projects

## Dependencies
- [x] move the `cli` commands about publishing message to frontend (or import `maci-cli` package) - see #12 
- [x] add support for user signups - see #4

## Requirements
- [x] allow badgeholders to add projects to /ballot page (already implemented in EasyRetroPGF)
- [x] allow badgeholders who have 1. connected their wallet & 2. signed up w/ MACI to submit their ballot
- [x] disable ability to vote if user has already submitted a ballot
- [x] Integrate maci sdk message publishing for saved ballot

## Details

For this demo, let's just assume the "happy path" that each badgeholder will only submit 1 ballot. Looks like the app already enforces this:
![Image 2024-01-29 at 13 48 56](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/8097623/897e3a2d-c173-4c92-9927-d8fddd4d9c18)

Submitting the ballot should trigger `publishMessage` on the Poll contract.

### Questions to sort out
- Do we need to submit a tx for every single project in the ballot, or how can we batch these messages (to reduce number of txs & gas costs)? clr.fund does some batching of their votes, so perhaps we can use a similar approach?
- Need to reverse array of votes, since they’re processed in reverse order? Sort out appropriate nonce for each

**Comment by samajammin** [comment]
> Do we need to submit a tx for every single project in the ballot, or how can we batch these messages (to reduce number of txs & gas costs)? clr.fund does some batching of their votes, so perhaps we can use a similar approach?

Looks like this is where they batch the messages: https://github.com/clrfund/monorepo/blob/develop/contracts/contracts/FundingRound.sol#L196

Then they call that from the frontend to submit votes/contributions:
https://github.com/clrfund/monorepo/blob/develop/vue-app/src/components/ContributionModal.vue#L194

We'll want to investigate how we might optimize this, so that a user is submitting as few on-chain txs as possible...
